<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h2><?php esc_html_e( 'User Permissions', 'power' ); ?></h2>
<table class="form-table">
	<tbody>
		<tr>
			<th scope="row"><?php esc_html_e( 'Power Admin Menus', 'power' ); ?></th>
			<td>
				<label for="power-meta[power_admin_menu]"><input id="power-meta[power_admin_menu]" name="power-meta[power_admin_menu]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'power_admin_menu', $object->ID ) ); ?> />
				<?php esc_html_e( 'Enable Power Admin Menu?', 'power' ); ?></label><br />

				<?php if ( ! power_seo_disabled() ) : ?>
				<label for="power-meta[power_seo_settings_menu]"><input id="power-meta[power_seo_settings_menu]" name="power-meta[power_seo_settings_menu]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'power_seo_settings_menu', $object->ID ) ); ?> />
					<?php esc_html_e( 'Enable SEO Settings Submenu?', 'power' ); ?></label><br />
				<?php endif; ?>

				<?php if ( current_theme_supports( 'power-import-export-menu' ) ) : ?>
				<label for="power-meta[power_import_export_menu]"><input id="power-meta[power_import_export_menu]" name="power-meta[power_import_export_menu]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'power_import_export_menu', $object->ID ) ); ?> />
					<?php esc_html_e( 'Enable Import/Export Submenu?', 'power' ); ?></label>
				<?php endif; ?>
			</td>
		</tr>
	</tbody>
</table>
