<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

$power_layout = get_the_author_meta( 'layout', $object->ID );
$power_layout = $power_layout ?: '';
?>
<h2><?php esc_html_e( 'Layout Settings', 'power' ); ?></h2>
<p><span class="description"><?php esc_html_e( 'These settings apply to this author\'s archive pages.', 'power' ); ?></span></p>
<table class="form-table">
	<tbody>
		<tr>
			<th scope="row"><?php esc_html_e( 'Choose Layout', 'power' ); ?></th>
			<td>
				<fieldset class="power-layout-selector">
					<legend class="screen-reader-text"><?php esc_html_e( 'Choose Layout', 'power' ); ?></legend>
					<p>
						<input type="radio" name="power-meta[layout]" class="default-layout" id="default-layout" value="" <?php checked( $power_layout, '' ); ?> />
						<label class="default" for="default-layout">
							<?php
							/* translators: %s: Theme settings admin screen link. */
							printf( esc_html__( 'Default Layout set in %s', 'power' ), '<a href="' . esc_url( menu_page_url( 'power', 0 ) ) . '">' . esc_html__( 'Theme Settings', 'power' ) . '</a>' );
							?>
						</label>
					</p>

					<?php
					power_layout_selector(
						[
							'name'     => 'power-meta[layout]',
							'selected' => $power_layout,
							'type'     => [ 'archive', 'author', $object->ID ],
						]
					);
					?>

				</fieldset>
			</td>
		</tr>
	</tbody>
</table>
