<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

$power_tax = get_taxonomy( $object->taxonomy );
?>
<h2><?php echo esc_html( $power_tax->labels->singular_name ) . ' ' . esc_html__( 'Archive Settings', 'power' ); ?></h2>
<table class="form-table">
	<tbody>
		<tr class="form-field">
			<th scope="row"><label for="power-meta[headline]"><?php esc_html_e( 'Archive Headline', 'power' ); ?></label></th>
			<td>
				<input name="power-meta[headline]" id="power-meta[headline]" type="text" value="<?php echo esc_attr( get_term_meta( $object->term_id, 'headline', true ) ); ?>" size="40" />
				<p class="description">
					<?php
					if ( power_a11y( 'headings' ) ) {
						esc_html_e( 'Your child theme uses accessible headings. If you leave this blank, the default accessible heading will be used.', 'power' );
					} else {
						esc_html_e( 'Leave empty if you do not want to display a headline.', 'power' );
					}
					?>
				</p>
			</td>
		</tr>
		<tr class="form-field">
			<th scope="row"><label for="power-meta-intro-text"><?php esc_html_e( 'Archive Intro Text', 'power' ); ?></label></th>
			<td>
				<?php
				wp_editor(
					get_term_meta( $object->term_id, 'intro_text', true ),
					'power-meta-intro-text',
					[
						'textarea_name' => 'power-meta[intro_text]',
					]
				);
				?>
				<p class="description"><?php esc_html_e( 'Leave empty if you do not want to display any intro text.', 'power' ); ?></p>
			</td>
		</tr>
	</tbody>
</table>
