<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h2><?php esc_html_e( 'Author Archive Settings', 'power' ); ?></h2>
<p><span class="description"><?php esc_html_e( 'These settings apply to this author\'s archive pages.', 'power' ); ?></span></p>
<table class="form-table">
	<tbody>
		<tr>
			<th scope="row"><label for="power-meta[headline]"><?php esc_html_e( 'Custom Archive Headline', 'power' ); ?></label></th>
			<td>
				<input name="power-meta[headline]" id="power-meta[headline]" type="text" value="<?php echo esc_attr( get_the_author_meta( 'headline', $object->ID ) ); ?>" class="regular-text" /><br />
				<span class="description">
				<?php
					/* translators: %s: Escaped h1 tag wrapped in code tags. */
					printf( esc_html__( 'Will display in the %s tag at the top of the first page', 'power' ), power_code( '<h1>' ) );
				?>
				</span>
			</td>
		</tr>

		<tr>
			<th scope="row"><label for="power-meta[intro-text]"><?php esc_html_e( 'Custom Description Text', 'power' ); ?></label></th>
			<td>
				<textarea name="power-meta[intro_text]" id="power-meta[intro-text]" rows="5" cols="30"><?php echo esc_textarea( get_the_author_meta( 'intro_text', $object->ID ) ); ?></textarea><br />
				<span class="description"><?php esc_html_e( 'This text will be the first paragraph, and display on the first page', 'power' ); ?></span>
			</td>
		</tr>

		<tr>
			<th scope="row"><?php esc_html_e( 'Author Box', 'power' ); ?></th>
			<td>
				<label for="power-meta[power_author_box_single]"><input id="power-meta[power_author_box_single]" name="power-meta[power_author_box_single]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'power_author_box_single', $object->ID ) ); ?> />
				<?php esc_html_e( 'Enable Author Box on this User\'s Posts?', 'power' ); ?></label><br />

				<label for="power-meta[power_author_box_archive]"><input id="power-meta[power_author_box_archive]" name="power-meta[power_author_box_archive]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'power_author_box_archive', $object->ID ) ); ?> />
				<?php esc_html_e( 'Enable Author Box on this User\'s Archives?', 'power' ); ?></label>
			</td>
		</tr>
	</tbody>
</table>
