<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

wp_nonce_field( 'power_inpost_layout_save', 'power_inpost_layout_nonce' );
?>
<table class="form-table">
<tbody>

<?php
if ( power_has_multiple_layouts() ) :
	$power_layout = power_get_custom_field( '_power_layout' );
	?>
	<tr>
		<th scope="row"><?php esc_html_e( 'Select Layout', 'power' ); ?></th>
		<td>
			<fieldset class="power-layout-selector">
				<legend class="screen-reader-text"><?php esc_html_e( 'Layout Settings', 'power' ); ?></legend>

				<p><input type="radio" name="power_layout[_power_layout]" class="default-layout" id="default-layout" value="" <?php checked( $power_layout, '' ); ?> /> <label class="default" for="default-layout">
					<?php
					/* translators: %s: Theme settings admin screen link. */
					printf( esc_html__( 'Default Layout set in %s', 'power' ), '<a href="' . esc_url( menu_page_url( 'power', 0 ) ) . '">' . esc_html__( 'Theme Settings', 'power' ) . '</a>' );
					?>
				</label></p>
				<?php

				power_layout_selector(
					[
						'name'     => 'power_layout[_power_layout]',
						'selected' => $power_layout,
						'type'     => [ 'singular', get_post_type(), get_the_ID() ],
					]
				);
				?>
			</fieldset>
		</td>
	</tr>
<?php endif; ?>

	<tr>
		<th scope="row"><label for="power_custom_body_class"><?php esc_html_e( 'Custom Body Class', 'power' ); ?></label></th>
		<td><p><input class="large-text" type="text" name="power_layout[_power_custom_body_class]" id="power_custom_body_class" value="<?php echo esc_attr( power_get_custom_field( '_power_custom_body_class' ) ); ?>" /></p></td>
	</tr>

	<tr>
		<th scope="row"><label for="power_custom_post_class"><?php esc_html_e( 'Custom Post Class', 'power' ); ?></label></th>
		<td><p><input class="large-text" type="text" name="power_layout[_power_custom_post_class]" id="power_custom_post_class" value="<?php echo esc_attr( power_get_custom_field( '_power_custom_post_class' ) ); ?>" /></p></td>
	</tr>

</tbody>
</table>
