<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h2><?php esc_html_e( 'Theme SEO Settings', 'power' ); ?></h2>
<table class="form-table">
	<tbody>
		<tr class="form-field">
			<th scope="row"><label for="power-meta[doctitle]"><?php esc_html_e( 'Custom Document Title', 'power' ); ?></label></th>
			<td>
				<input name="power-meta[doctitle]" id="power-meta[doctitle]" type="text" value="<?php echo esc_attr( get_term_meta( $object->term_id, 'doctitle', true ) ); ?>" size="40" />
				<p class="description"><?php esc_html_e( 'The Custom Document Title sets the page title as seen in browsers and search engines. ', 'power' ); ?></p>
			</td>
		</tr>

		<tr class="form-field">
			<th scope="row"><label for="power-meta[description]"><?php esc_html_e( 'Meta Description', 'power' ); ?></label></th>
			<td>
				<textarea name="power-meta[description]" id="power-meta[description]" rows="5" cols="50" class="large-text"><?php echo esc_html( get_term_meta( $object->term_id, 'description', true ) ); ?></textarea>
				<p class="description"><?php esc_html_e( 'Text entered in the Meta Description field is used as the short page description under the title on search engine results pages.', 'power' ); ?></p>
			</td>
		</tr>

		<tr class="form-field">
			<th scope="row"><label for="power-meta[keywords]"><?php esc_html_e( 'Meta Keywords', 'power' ); ?></label></th>
			<td>
				<input name="power-meta[keywords]" id="power-meta[keywords]" type="text" value="<?php echo esc_attr( get_term_meta( $object->term_id, 'keywords', true ) ); ?>" size="40" />
				<p class="description"><?php esc_html_e( 'A comma-separated list of keywords relevant to the page can be entered in the Meta Keywords field. Keywords are generally ignored by Search Engines.', 'power' ); ?></p>
			</td>
		</tr>

		<tr>
			<th scope="row"><?php esc_html_e( 'Robots Meta', 'power' ); ?>
				<a href="https://yoast.com/robots-meta-tags/" target="_blank" rel="noopener noreferrer">[?]</a>
			</th>
			<td>
				<label for="power-meta[noindex]"><input name="power-meta[noindex]" id="power-meta[noindex]" type="checkbox" value="1" <?php checked( get_term_meta( $object->term_id, 'noindex', true ) ); ?> />
				<?php
					/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
					printf( esc_html__( 'Apply %s to this archive?', 'power' ), power_code( 'noindex' ) );
				?>
				</label><br />

				<label for="power-meta[nofollow]"><input name="power-meta[nofollow]" id="power-meta[nofollow]" type="checkbox" value="1" <?php checked( get_term_meta( $object->term_id, 'nofollow', true ) ); ?> />
				<?php
					/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
					printf( esc_html__( 'Apply %s to this archive?', 'power' ), power_code( 'nofollow' ) );
				?>
				</label><br />

				<label for="power-meta[noarchive]"><input name="power-meta[noarchive]" id="power-meta[noarchive]" type="checkbox" value="1" <?php checked( get_term_meta( $object->term_id, 'noarchive', true ) ); ?> />
				<?php
					/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
					printf( esc_html__( 'Apply %s to this archive?', 'power' ), power_code( 'noarchive' ) );
				?>
				</label>
			</td>
		</tr>
	</tbody>
</table>
