<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

wp_nonce_field( 'power_inpost_seo_save', 'power_inpost_seo_nonce' );
?>

<table class="form-table">
<tbody>

	<tr>
		<th scope="row"><label for="power_title"><?php esc_html_e( 'Document Title', 'power' ); ?><span class="screen-reader-text"> &lt;title&gt; Tag. </span></label></th>
		<td>
			<p><input class="large-text" type="text" name="power_seo[_power_title]" id="power_title" value="<?php echo esc_attr( power_get_custom_field( '_power_title' ) ); ?>" /></p>
			<p class="description"><?php esc_html_e( 'The Custom Document Title sets the page title as seen in browsers and search engines. ', 'power' ); ?></p>
			<p><span class="hide-if-no-js description">
				<?php
				/* translators: %s: String length */
				printf( esc_html__( 'Characters Used: %s', 'power' ), '<span id="power_title_chars">' . esc_html( mb_strlen( power_get_custom_field( '_power_title' ) ) ) . '</span>' );
				?>
			</span></p>
		</td>
	</tr>

	<tr>
		<th scope="row"><label for="power_description"><?php esc_html_e( 'Meta Description', 'power' ); ?><span class="screen-reader-text"> &lt;meta name=&quot;description&quot; /&gt;. </span></label></th>
		<td>
			<p><textarea class="widefat" name="power_seo[_power_description]" id="power_description" rows="4" cols="4"><?php echo esc_textarea( power_get_custom_field( '_power_description' ) ); ?></textarea></p>
			<p class="description"><?php esc_html_e( 'Text entered in the Meta Description field is used as the short page description under the title on search engine results pages.', 'power' ); ?></p>
			<p><span class="hide-if-no-js description">
				<?php
				/* translators: %s: String length */
				printf( esc_html__( 'Characters Used: %s', 'power' ), '<span id="power_description_chars">' . esc_html( mb_strlen( power_get_custom_field( '_power_description' ) ) ) . '</span>' );
				?>
			</span></p>
		</td>
	</tr>

	<tr>
		<th scope="row"><label for="power_keywords"><strong><?php esc_html_e( 'Meta Keywords', 'power' ); ?></strong><span class="screen-reader-text"> &lt;meta name=&quot;keywords&quot; /&gt;. </span></label></th>
		<td>
			<p><input class="large-text" type="text" name="power_seo[_power_keywords]" id="power_keywords" value="<?php echo esc_attr( power_get_custom_field( '_power_keywords' ) ); ?>" /></p>
			<p class="description"><?php esc_html_e( 'A comma-separated list of keywords relevant to the page can be entered in the Meta Keywords field. Keywords are generally ignored by Search Engines.', 'power' ); ?></p>
		</td>
	</tr>

	<tr>
		<th scope="row"><label for="power_canonical"><strong><?php esc_html_e( 'Canonical URL', 'power' ); ?></strong> <span class="screen-reader-text"> &lt;link rel=&quot;canonical&quot; /&gt;. </span></label></th>
		<td><p><input class="large-text" type="text" name="power_seo[_power_canonical_uri]" id="power_canonical" value="<?php echo esc_url( power_get_custom_field( '_power_canonical_uri' ) ); ?>" /></p></td>
	</tr>

	<tr>
		<th scope="row"><label for="power_redirect"><strong><?php esc_html_e( 'Custom Redirect URL', 'power' ); ?></strong><span class="screen-reader-text"> <?php esc_html_e( '301 Redirect.', 'power' ); ?> </span></label></th>
		<td><p><input class="large-text" type="text" name="power_seo[redirect]" id="power_redirect" value="<?php echo esc_url( power_get_custom_field( 'redirect' ) ); ?>" /></p></td>
	</tr>

	<tr>
		<th scope="row"><?php esc_html_e( 'Robots Meta Settings', 'power' ); ?>
			<a href="https://yoast.com/robots-meta-tags/" target="_blank" rel="noopener noreferrer">[?]</a>
		</th>
		<td>
			<p>
				<label for="power_noindex"><input type="checkbox" name="power_seo[_power_noindex]" id="power_noindex" value="1" <?php checked( power_get_custom_field( '_power_noindex' ) ); ?> />
				<?php
				/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
				printf( esc_html__( 'Apply %s to this post/page', 'power' ), power_code( 'noindex' ) );
				?>
				</label><br />
			</p>
			<p>
				<label for="power_nofollow"><input type="checkbox" name="power_seo[_power_nofollow]" id="power_nofollow" value="1" <?php checked( power_get_custom_field( '_power_nofollow' ) ); ?> />
				<?php
				/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
				printf( esc_html__( 'Apply %s to this post/page', 'power' ), power_code( 'nofollow' ) );
				?>
				</label><br />
			</p>
			<p>
				<label for="power_noarchive"><input type="checkbox" name="power_seo[_power_noarchive]" id="power_noarchive" value="1" <?php checked( power_get_custom_field( '_power_noarchive' ) ); ?> />
				<?php
				/* translators: %s: robots meta content attribute value, such as 'noindex', 'nofollow' or 'noarchive'. */
				printf( esc_html__( 'Apply %s to this post/page', 'power' ), power_code( 'noarchive' ) );
				?>
				</label>
			</p>
		</td>
	</tr>

</tbody>
</table>
