<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h2><?php esc_html_e( 'Layout Settings', 'power' ); ?></h2>

<table class="form-table">
	<tbody>
		<tr>
			<th scope="row"><?php esc_html_e( 'Choose Layout', 'power' ); ?></th>
			<td>
				<fieldset class="power-layout-selector">
					<legend class="screen-reader-text"><?php esc_html_e( 'Choose Layout', 'power' ); ?></legend>

					<p><input type="radio" class="default-layout" name="power-meta[layout]" id="default-layout" value="" <?php checked( get_term_meta( $object->term_id, 'layout', true ), '' ); ?> /> <label for="default-layout" class="default">
					<?php
					/* translators: %s: Theme settings admin screen link. */
					printf( esc_html__( 'Default Layout set in %s', 'power' ), '<a href="' . esc_url( menu_page_url( 'power', 0 ) ) . '">' . esc_html__( 'Theme Settings', 'power' ) . '</a>' );
					?>
					</label></p>
					<?php
					power_layout_selector(
						[
							'name'     => 'power-meta[layout]',
							'selected' => get_term_meta( $object->term_id, 'layout', true ),
							'type'     => [ 'archive', $object->taxonomy, $object->term_id ],
						]
					);
					?>
				</fieldset>
			</td>
		</tr>
	</tbody>
</table>
