<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

wp_nonce_field( 'power_inpost_adsense_save', 'power_inpost_adsense_nonce' );
?>
<table class="form-table">
	<tbody>
	<tr>
		<th scope="row">
			<strong><?php esc_html_e( 'AdSense Output', 'power' ); ?></strong>
		</th>
		<td>
			<input type="hidden" name="power_adsense[key]" value="1" />
			<input type="checkbox" name="power_adsense[_disable_adsense]" id="power_adsense[_disable_adsense]" value="1" <?php checked( power_get_custom_field( '_disable_adsense' ) ); ?> />
			<label for="power_adsense[_disable_adsense]"><?php esc_html_e( 'Disable AdSense output for this entry?', 'power' ); ?></label>
		</td>
	</tr>
	</tbody>
</table>
