<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Templates
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    https://www.daniellane.eu
 */

if ( post_password_required() ) {
	printf( '<p class="alert">%s</p>', esc_html__( 'This post is password protected. Enter the password to view comments.', 'power' ) );
	return;
}

// Output semantically correct header if accessibility is supported.
if ( power_a11y( 'headings' ) ) {
	printf( '<h2 class="screen-reader-text">%s</h2>', esc_html__( 'Reader Interactions', 'power' ) );
}

/**
 * Fires before the main comments action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_before_comments' );

/**
 * Fires to display the main comments content.
 *
 * @since 1.1.2
 */
do_action( 'power_comments' );

/**
 * Fires after the main comments action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_after_comments' );

/**
 * Fires before the main pings action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_before_pings' );

/**
 * Fires to display the main pings content.
 *
 * @since 1.1.2
 */
do_action( 'power_pings' );

/**
 * Fires after the main pings action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_after_pings' );

/**
 * Fires before the main comment form action hook.
 *
 * @since 1.1.0
 */
do_action( 'power_before_comment_form' );

/**
 * Fires to display the main comment form content.
 *
 * @since 1.1.0
 */
do_action( 'power_comment_form' );

/**
 * Fires after the main comment form action hook.
 *
 * @since 1.1.0
 */
do_action( 'power_after_comment_form' );
