<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Templates
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

power_structural_wrap( 'site-inner', 'close' );
power_markup(
	[
		'close'   => '</div>',
		'context' => 'site-inner',
	]
);

/**
 * Fires immediately after the site inner closing markup, before `power_footer` action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_before_footer' );

/**
 * Fires to display the main footer content.
 *
 * @since 1.0.1
 */
do_action( 'power_footer' );

/**
 * Fires immediately after the `power_footer` action hook, before the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'power_after_footer' );

power_markup(
	[
		'close'   => '</div>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately before wp_footer(), after the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'power_after' );
wp_footer(); // We need this for plugins.

power_markup(
	[
		'close'   => '</body>',
		'context' => 'body',
	]
);

?>
</html>
