<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Templates
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Fires at start of header.php, immediately before `power_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action( 'power_doctype' );

/**
 * Fires immediately after `power_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action( 'power_title' );

/**
 * Fires immediately after `power_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action( 'power_meta' );

wp_head(); // We need this for plugins.
?>
</head>
<?php
power_markup(
	[
		'open'    => '<body %s>',
		'context' => 'body',
	]
);

if ( function_exists( 'wp_body_open' ) ) {
	wp_body_open();
}

/**
 * Fires immediately after the `wp_body_open` action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_before' );

power_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately after the site container opening markup, before `power_header` action hook.
 *
 * @since 1.0.0
 */
do_action( 'power_before_header' );

/**
 * Fires to display the main header content.
 *
 * @since 1.0.2
 */
do_action( 'power_header' );

/**
 * Fires immediately after the `power_header` action hook, before the site inner opening markup.
 *
 * @since 1.0.0
 */
do_action( 'power_after_header' );

power_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-inner',
	]
);
power_structural_wrap( 'site-inner' );
