<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Templates
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

// Output secondary sidebar structure.
power_markup(
	[
		'open'    => '<aside %s>' . power_sidebar_title( 'sidebar-alt' ),
		'context' => 'sidebar-secondary',
	]
);

/**
 * Fires immediately after the Secondary Sidebar opening markup.
 *
 * @since 1.0.0
 */
do_action( 'power_before_sidebar_alt_widget_area' );

/**
 * Fires to display the main Secondary Sidebar content.
 *
 * @since 1.2.0
 */
do_action( 'power_sidebar_alt' );

/**
 * Fires immediately before the Secondary Sidebar closing markup.
 *
 * @since 1.0.0
 */
do_action( 'power_after_sidebar_alt_widget_area' );

// End .sidebar-secondary.
power_markup(
	[
		'close'   => '</aside>',
		'context' => 'sidebar-secondary',
	]
);
