<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    wwww.daniellane.eu
 */

$power_active_theme = wp_get_theme();
?>
<div class="wrap">
	<div class="power-onboarding-page-wrap power-onboarding-page-starter-packs">
		<main class="power-onboarding-main">
			<h1 class="power-onboarding-intro-title">
				<?php
				/* translators: %s: Theme name */
				echo esc_html( sprintf( __( 'Get started with %s.', 'power' ), $power_active_theme['Name'] ) );
				?>
			</h1>
			<div class="power-onboarding-intro-text">
				<p>
				<?php
				/* translators: %s: Theme name */
				echo esc_html( sprintf( __( '%s offers a choice of starter packs. A starter pack is a bundle of content and/or plugins that will be automatically imported and set up for you.', 'power' ), $power_active_theme['Name'] ) );
				?>
				</p>
				<p>
				<strong>
				<?php esc_html_e( 'Click on the images below to learn more about each Starter Pack and choose the pack that best suits your needs.', 'power' ); ?>
				</strong>
				<?php esc_html_e( 'None of your existing content will be lost. Find this page again at Power → Child Theme Setup.', 'power' ); ?>
				</p>
			</div>
			<div class="power-onboarding-progress-bar-wrapper">
				<span id="power-onboarding-progress-bar"></span>
			</div>

			<div class="power-onboarding-starter-packs">
				<?php power_onboarding_starter_packs_list(); ?>
			</div>

			<ul class="power-onboarding-list">
				<li class="power-onboarding-task-dependencies power-onboarding-area-hidden">
					<div class="power-onboarding-task-steps">
						<div class="power-onboarding-step-one"></div>
						<div class="power-onboarding-step-two">
							<svg class="power-onboarding-list-spinner" viewBox="0 0 50 50" aria-hidden="true">
								<circle class="path" cx="25" cy="25" r="23" fill="none" stroke-width="4"></circle>
							</svg>
						</div>
						<div class="power-onboarding-step-three">
							<svg style="width:40px; height:40px;" viewBox="0 0 10 10" aria-hidden="true">
								<circle cx="5" cy="5" r="4.5" style="stroke:#6c8196; stroke-width:0.7; fill:none;"></circle>
								<polyline points="2.7,5 4.2,6.7 7.5,3.6" style="stroke:#6c8196; stroke-width:0.7; stroke-linejoin:round; stroke-linecap:round; fill:none;"></polyline>
							</svg>
						</div>
					</div>

					<h3><?php esc_html_e( 'Recommended plugins', 'power' ); ?></h3>
					<p><?php esc_html_e( 'Installing and activating plugins for your starter pack.', 'power' ); ?></p>
				</li>

				<li class="power-onboarding-task-content power-onboarding-area-hidden">
					<div class="power-onboarding-task-steps">
						<div class="power-onboarding-step-one"></div>
						<div class="power-onboarding-step-two">
							<svg class="power-onboarding-list-spinner" viewBox="0 0 50 50" aria-hidden="true">
								<circle class="path" cx="25" cy="25" r="23" fill="none" stroke-width="4"></circle>
							</svg>
						</div>
						<div class="power-onboarding-step-three">
							<svg style="width:40px; height:40px;" viewBox="0 0 10 10" aria-hidden="true">
								<circle cx="5" cy="5" r="4.5" style="stroke:#6c8196; stroke-width:0.7; fill:none;"></circle>
								<polyline points="2.7,5 4.2,6.7 7.5,3.6" style="stroke:#6c8196; stroke-width:0.7; stroke-linejoin:round; stroke-linecap:round; fill:none;"></polyline>
							</svg>
						</div>
					</div>

					<h3><?php esc_html_e( 'Demo content', 'power' ); ?></h3>
					<p>
						<?php
						esc_html_e( 'Adding sample content to make your theme look like the chosen starter pack.', 'power' );
						?>
					</p>
				</li>

				<li class="power-onboarding-task-final">
					<div class="power-onboarding-task-steps">
						<div class="power-onboarding-step-one"></div>
						<div class="power-onboarding-step-two">
							<svg class="power-onboarding-list-spinner" viewBox="0 0 50 50" aria-hidden="true">
								<circle class="path" cx="25" cy="25" r="23" fill="none" stroke-width="4"></circle>
							</svg>
						</div>
						<div class="power-onboarding-step-three">
							<svg style="width:40px; height:40px;" viewBox="0 0 10 10" aria-hidden="true">
								<circle cx="5" cy="5" r="4.5" style="stroke:#6c8196; stroke-width:0.7; fill:none;"></circle>
								<polyline points="2.7,5 4.2,6.7 7.5,3.6" style="stroke:#6c8196; stroke-width:0.7; stroke-linejoin:round; stroke-linecap:round; fill:none;"></polyline>
							</svg>
						</div>
					</div>

					<h3><?php esc_html_e( 'All done!', 'power' ); ?></h3>
					<p><?php esc_html_e( 'Your starter pack installation is complete! View or edit your homepage using the buttons below.', 'power' ); ?></p>

					<a id="power-onboarding-view-homepage" class="power-onboarding-button power-onboarding-button-blue" href="<?php echo esc_url( home_url() ); ?>"><?php esc_html_e( 'View your homepage', 'power' ); ?></a>
					<a id="power-onboarding-edit-homepage" class="power-onboarding-button power-onboarding-button-blue" href="#"><?php esc_html_e( 'Edit your homepage', 'power' ); ?></a>
				</li>
			</ul>
		</main>

	</div><!-- .power-onboarding-page-wrap -->
</div>
