<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<div class="wrap">
	<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>

	<table class="form-table">
		<tbody>

			<tr>
				<th scope="row"><strong><?php esc_html_e( 'Import Power Settings File', 'power' ); ?></strong></th>
				<td>
					<p>
					<?php
					/* translators: %s: JSON file extension. */
					printf( esc_html__( 'Upload the data file (%s) from your computer and we\'ll import your settings.', 'power' ), power_code( '.json' ) );
					?>
					</p>
					<p><?php esc_html_e( 'Choose the file from your computer and click "Upload file and Import"', 'power' ); ?></p>

						<form enctype="multipart/form-data" method="post" action="<?php echo esc_url( menu_page_url( 'power-import-export', 0 ) ); ?>">
							<?php wp_nonce_field( 'power-import', 'power-import-nonce' ); ?>
							<input type="hidden" name="power-import" value="1" />
							<label for="power-import-upload">
								<?php
								/* translators: %s: Maximum size import files can have. */
								printf( esc_html__( 'Upload File (Maximum Size: %s): ', 'power' ), esc_html( ini_get( 'post_max_size' ) ) );
								?>
							</label>
							<input type="file" id="power-import-upload" name="power-import-upload" />
							<?php
							submit_button( __( 'Upload File and Import', 'power' ), 'primary', 'upload' );
							?>
						</form>

				</td>
			</tr>

			<tr>
				<th scope="row"><strong><?php esc_html_e( 'Export Power Settings File', 'power' ); ?></strong></th>
				<td>
					<p>
					<?php
					/* translators: %s: JSON file extension. */
					printf( esc_html__( 'When you click the button below, Power will generate a data file (%s) for you to save to your computer.', 'power' ), power_code( '.json' ) );
					?>
					</p>
					<p><?php esc_html_e( 'Once you have saved the download file, you can use the import function on another site to import this data.', 'power' ); ?></p>

						<form method="post" action="<?php echo esc_url( menu_page_url( 'power-import-export', 0 ) ); ?>">
							<?php
							wp_nonce_field( 'power-export', 'power-export-nonce' );
							$this->export_checkboxes();
							if ( $this->get_export_options() ) {
								submit_button( __( 'Download Export File', 'power' ), 'primary', 'download' );
							}
							?>
						</form>

				</td>
			</tr>

			<?php
			/**
			 * Fires on the import export admin page, before the closing tbody tag.
			 *
			 * @since 1.6.0
			 */
			do_action( 'power_import_export_form' );
			?>

		</tbody>
	</table>

</div>
