<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Assets
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Retrieve a handle to the script loader.
 *
 * @since 2.5.0
 *
 * @return Power_Script_Loader object
 */
function power_scripts() {

	static $_power_scripts = null;

	if ( null === $_power_scripts ) {

		$_power_scripts = new Power_Script_Loader();
		$_power_scripts->add_hooks();

	}

	return $_power_scripts;

}

power_scripts();
