<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Upgrade class. Called when `db_version` Power setting is below 1700.
 *
 * @since 3.1.0
 */
class Upgrade_DB_1700 implements Upgrade_DB_Interface {
	/**
	 * Upgrade method.
	 *
	 * @since 1.7.0
	 * @since 3.1.0 Moved to class method.
	 */
	public function upgrade() {
		global $wpdb;

		// Changing the UI. Remove old user options.
		$wpdb->query( $wpdb->prepare( "DELETE FROM $wpdb->usermeta WHERE meta_key = %s OR meta_key = %s", 'meta-box-order_toplevel_page_power', 'meta-box-order_power_page_seosettings' ) );
		$wpdb->query( $wpdb->prepare( "UPDATE $wpdb->usermeta SET meta_value = %s WHERE meta_key = %s OR meta_key = %s", '1', 'screen_layout_toplevel_page_power', 'screen_layout_power_page_seosettings' ) );
	}
}
