<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Upgrade class. Called when `db_version` Power setting is below 2207.
 *
 * @since 3.1.0
 */
class Upgrade_DB_2207 implements Upgrade_DB_Interface {
	/**
	 * Upgrade method.
	 *
	 * @since 2.2.4
	 * @since 3.1.0 Moved to class method.
	 */
	public function upgrade() {
		$update_email_address = power_get_option( 'update_email' ) ? power_get_option( 'update_email_address' ) : '';

		power_update_settings(
			[
				'update_email'         => 'unset',
				'update_email_address' => $update_email_address,
			]
		);
	}
}
