<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Interface for all database upgraders.
 *
 * @since 3.1.0
 */
interface Upgrade_DB_Interface {
	/**
	 * The upgrade method. Required for all implementations of this interface.
	 *
	 * @since 3.1.0
	 */
	public function upgrade();
}
