<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Upgrade class. Called when `db_version` Power setting is below 130.
 *
 * @since 3.1.0
 */
class Upgrade_DB_130 implements Upgrade_DB_Interface {
	/**
	 * Upgrade method.
	 *
	 * @since 1.3.0
	 * @since 3.1.0 Moved to class method.
	 */
	public function upgrade() {
		power_update_settings(
			[
				'author_box_single' => power_get_option( 'author_box' ),
			]
		);

		power_update_settings(
			[
				'noindex_cat_archive'    => power_get_seo_option( 'index_cat_archive' ) ? 0 : 1,
				'noindex_tag_archive'    => power_get_seo_option( 'index_tag_archive' ) ? 0 : 1,
				'noindex_author_archive' => power_get_seo_option( 'index_author_archive' ) ? 0 : 1,
				'noindex_date_archive'   => power_get_seo_option( 'index_date_archive' ) ? 0 : 1,
				'noindex_search_archive' => power_get_seo_option( 'index_search_archive' ) ? 0 : 1,
				'noodp'                  => 1,
				'noydir'                 => 1,
				'canonical_archives'     => 1,
			],
			POWER_SEO_SETTINGS_FIELD
		);

		delete_transient( 'power-remote-store' );
	}
}
