<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Upgrade class. Called when `db_version` Power setting is below 3100.
 *
 * @since 3.1.0
 */
class Upgrade_DB_3100 implements Upgrade_DB_Interface {
	/**
	 * Upgrade method.
	 *
	 * @since 3.1.0
	 */
	public function upgrade() {
		$this->create_footer_setting();
		$this->unset_noodp_noydir();
	}

	/**
	 * Create the footer setting with proper default.
	 *
	 * @since 3.1.0
	 */
	public function create_footer_setting() {
		$footer_text_default   = sprintf( '[footer_copyright before="%s "] · [footer_childtheme_link before="" after=" %s"] [footer_power_link url="https://www.coreengine.com/" before=""] · [footer_wordpress_link] · [footer_loginout]', __( 'Copyright', 'power' ), __( 'on', 'power' ) );
		$old_footer_creds_text = defined( 'GSE_SETTINGS_FIELD' ) ? power_get_option( 'footer_creds_text', GSE_SETTINGS_FIELD ) : apply_filters( 'power_footer_creds_text', null );

		power_update_settings(
			[
				'footer_text' => $old_footer_creds_text ?: $footer_text_default,
			]
		);
	}

	/**
	 * Unset `noodp` and `noydir` SEO settings. They were removed.
	 *
	 * @since 3.1.0
	 */
	public function unset_noodp_noydir() {
		// `noodp` and `noydir` settings were removed: https://github.com/coreengine/power/issues/2347
		power_update_settings(
			[
				'noodp'  => 'unset',
				'noydir' => 'unset',
			],
			POWER_SEO_SETTINGS_FIELD
		);
	}
}
