<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

namespace CoreEngine\Power\Upgrade;

/**
 * Upgrade class. Called when `db_version` Power setting is below 2209.
 *
 * @since 3.1.0
 */
class Upgrade_DB_2209 implements Upgrade_DB_Interface {
	/**
	 * Upgrade method.
	 *
	 * @since 2.2.6
	 * @since 3.1.0 Moved to class method.
	 */
	public function upgrade() {
		$term_meta = get_option( 'power-term-meta' );

		foreach ( (array) $term_meta as $term_id => $meta ) {
			foreach ( (array) $meta as $key => $value ) {
				add_term_meta( $term_id, $key, $value, true );
			}
		}
	}
}
