<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Manage Power Core Framework via cli.
 */
class Power_Cli_Core_Command {
	/**
	 * Show current Power core files version
	 *
	 * ## CORE
	 *
	 * ## EXAMPLES
	 *
	 *  $ wp power core version
	 *  2.9.1
	 *
	 * @subcommand version
	 *
	 * @since 2.10.0
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Stores all the arguments defined like --key=value or --flag or --no-flag.
	 */
	public function version( $args, $assoc_args ) {

		WP_CLI::log( PARENT_THEME_VERSION );

	}

	/**
	 * Updates Power, upgrades the database.
	 *
	 * ## EXAMPLES
	 *
	 *  $ wp power core update
	 *
	 * @since 2.10.0
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Stores all the arguments defined like --key=value or --flag or --no-flag.
	 */
	public function update( $args, $assoc_args ) {

		// Clear the transient to force a check in the API.
		power_clear_update_transient();

		WP_CLI::runcommand( 'theme update power' );
		WP_CLI::runcommand( 'power db upgrade' );

	}
}
