<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Registers a new admin page, providing content and corresponding menu item for the "What's new" page.
 *
 * @package Power\Admin
 *
 * @since 1.9.0
 */
class Power_Admin_Upgraded extends Power_Admin_Basic {

	/**
	 * Create the page.
	 *
	 * @since 1.9.0
	 */
	public function __construct() {

		$page_id = 'power-upgraded';

		$menu_ops = [
			'submenu' => [
				'parent_slug' => 'admin.php',
				'menu_title'  => '',
				/* translators: %s: Power version. */
				'page_title'  => sprintf( __( 'Welcome to Power %s', 'power' ), PARENT_THEME_BRANCH ),
			],
		];

		$this->create( $page_id, $menu_ops );

		add_action( 'admin_enqueue_scripts', 'add_thickbox' );

	}

	/**
	 * Required to use `Power_Admin_Basic`.
	 *
	 * @since 1.9.0
	 */
	public function admin() {
		require_once $this->views_base . '/pages/power-admin-upgraded.php';
	}

}
