<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Manage Power Framework via cli - Backward compatibility.
 */
class Power_Cli_Command {
	/**
	 * Upgrade the database settings for Power, usually after an update.
	 *
	 * ## EXAMPLES
	 *
	 *  $ wp power upgrade-db
	 *  Success: Power database upgraded.
	 *
	 * @subcommand upgrade-db
	 * @alias upgrade_db
	 *
	 * @since 2.2.0
	 * @since 2.4.0 Command now invoked with `upgrade-db`, not `upgrade_db`, per WP-CLI standard.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Stores all the arguments defined like --key=value or --flag or --no-flag.
	 */
	public function upgrade_db( $args, $assoc_args ) {
		WP_CLI::runcommand( 'power db upgrade' );
	}
}
