<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Registers a new admin menu item under "Power". Redirects to the plugin install screen filtered to return plugins authored by CoreEngine.
 *
 * @since 2.10.0
 */
class Power_Admin_Plugins extends Power_Admin_Basic {

	/**
	 * Create an admin menu item that redirects to the plugin install screen.
	 *
	 * @since 2.10.0
	 */
	public function __construct() {
		$this->redirect_to = network_admin_url( 'plugin-install.php?s=coreengine&tab=search&type=author' );

		$menu_ops = [
			'submenu' => [
				'parent_slug' => 'power',
				'page_title'  => __( 'Power Plugins', 'power' ),
				'menu_title'  => __( 'Power Plugins', 'power' ),
			],
		];

		$this->create( 'power-plugins', $menu_ops );
	}

	/**
	 * Required to use `Power_Admin_Basic`.
	 *
	 * @since 2.10.0
	 */
	public function admin() {}

}
