<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Registers a new admin page, providing content and corresponding menu item for the "Getting Started" page.
 *
 * @since 2.8.0
 */
final class Power_Admin_Onboarding extends Power_Admin_Basic {

	/**
	 * Sets the admin page properties and creates the page.
	 */
	public function __construct() {
		$this->help_base = POWER_VIEWS_DIR . '/help/getting-started-';

		$page_id = 'power-getting-started';

		$menu_ops = [
			'submenu' => [
				'parent_slug' => 'power',
				'page_title'  => __( 'Power - Getting Started', 'power' ),
				'menu_title'  => __( 'Child Theme Setup', 'power' ),
			],
		];

		$this->create( $page_id, $menu_ops );
	}

	/**
	 * Loads the onboarding admin page.
	 */
	public function admin() {
		if ( power_onboarding_starter_packs() ) {
			delete_option( 'power_onboarding_chosen_pack' );
			include POWER_VIEWS_DIR . '/pages/power-admin-onboarding-packs.php';
		} else {
			include POWER_VIEWS_DIR . '/pages/power-admin-onboarding.php';
		}
	}

}
