<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Manage Power Framework database via cli.
 */
class Power_Cli_Db_Command {
	/**
	 * Upgrade the database settings for Power, usually after an update.
	 *
	 * ## DB
	 *
	 * ## EXAMPLES
	 *
	 *  $ wp power db upgrade
	 *  Success: Power database upgraded.
	 *
	 * @subcommand upgrade
	 *
	 * @since 2.10.0
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Stores all the arguments defined like --key=value or --flag or --no-flag.
	 */
	public function upgrade( $args, $assoc_args ) {

		// Disable post-upgrade redirect.
		remove_action( 'power_upgrade', 'power_upgrade_redirect' );

		// Call the upgrade function.
		power_upgrade();

		WP_CLI::success( __( 'Power database upgraded.', 'power' ) );

	}

	/**
	 * Show current Power database version
	 *
	 * ## DB
	 *
	 * ## EXAMPLES
	 *
	 *  $ wp power db version
	 *  Success: Version 2.10.0
	 *
	 * @subcommand version
	 *
	 * @since 2.10.0
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Stores all the arguments defined like --key=value or --flag or --no-flag.
	 */
	public function version( $args, $assoc_args ) {

		WP_CLI::log( PARENT_DB_VERSION );

	}
}
