<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Registers a new admin page, providing content and corresponding menu item for the Theme Settings page.
 *
 * Although this class was added in 1.8.0, some of the methods were originally* standalone functions added in previous
 * versions of Power.
 *
 * @package Power\Admin
 *
 * @since 1.8.0
 */
class Power_Admin_Settings extends Power_Admin_Basic {

	/**
	 * Create an admin menu item and settings page.
	 *
	 * @since 1.8.0
	 */
	public function __construct() {

		$this->redirect_to = admin_url( 'customize.php?autofocus[panel]=power' );

		$page_id = 'power';

		$menu_ops = apply_filters(
			'power_theme_settings_menu_ops',
			[
				'main_menu'     => [
					'sep'        => [
						'sep_position'   => '58.995',
						'sep_capability' => 'edit_theme_options',
					],
					'page_title' => 'Theme Settings',
					'menu_title' => 'Power',
					'capability' => 'edit_theme_options',
					'icon_url'   => POWER_ADMIN_IMAGES_URL . '/power-menu.png',
					'position'   => '58.996',
				],
				'first_submenu' => [ // Do not use without 'main_menu'.
					'page_title' => __( 'Theme Settings', 'power' ),
					'menu_title' => __( 'Theme Settings', 'power' ),
					'capability' => 'edit_theme_options',
				],
			]
		);

		$this->create( $page_id, $menu_ops );

	}

	/**
	 * Required to use `Power_Admin_Basic`.
	 *
	 * @since 3.0
	 */
	public function admin() {}
}
