<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Framework
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Used to initialize the framework in the various template files.
 *
 * It pulls in all the necessary components like header and footer, the basic
 * markup structure, and hooks.
 *
 * @since 1.3.0
 */
function power() {

	get_header();

	/**
	 * Fires after the header, before the content sidebar wrap.
	 *
	 * @since 1.0.0
	 */
	do_action( 'power_before_content_sidebar_wrap' );

	power_markup(
		[
			'open'    => '<div %s>',
			'context' => 'content-sidebar-wrap',
		]
	);

		/**
		 * Fires before the content, after the content sidebar wrap opening markup.
		 *
		 * @since 1.0.0
		 */
		do_action( 'power_before_content' );

		power_markup(
			[
				'open'    => '<main %s>',
				'context' => 'content',
			]
		);

			/**
			 * Fires before the loop hook, after the main content opening markup.
			 *
			 * @since 1.0.0
			 */
			do_action( 'power_before_loop' );

			/**
			 * Fires to display the loop contents.
			 *
			 * @since 1.1.0
			 */
			do_action( 'power_loop' );

			/**
			 * Fires after the loop hook, before the main content closing markup.
			 *
			 * @since 1.0.0
			 */
			do_action( 'power_after_loop' );

		power_markup(
			[
				'close'   => '</main>', // End .content.
				'context' => 'content',
			]
		);

		/**
		 * Fires after the content, before the main content sidebar wrap closing markup.
		 *
		 * @since 1.0.0
		 */
		do_action( 'power_after_content' );

	power_markup(
		[
			'close'   => '</div>',
			'context' => 'content-sidebar-wrap',
		]
	);

	/**
	 * Fires before the footer, after the content sidebar wrap.
	 *
	 * @since 1.0.0
	 */
	do_action( 'power_after_content_sidebar_wrap' );

	get_footer();

}
