<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Menus
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_filter( 'nav_menu_link_attributes', 'power_nav_menu_link_attributes' );
/**
 * Pass nav menu link attributes through attribute parser.
 *
 * Adds nav menu link attributes via the Power markup API.
 *
 * @since 2.2.0
 *
 * @param array $atts {
 *      The HTML attributes applied to the menu item's link element, empty strings are ignored.
 *
 *      @type string $title Title attribute.
 *      @type string $target Target attribute.
 *      @type string $rel The rel attribute.
 *      @type string $href The href attribute.
 * }
 * @return array Maybe modified menu attributes array.
 */
function power_nav_menu_link_attributes( $atts ) {

	return power_parse_attr( 'nav-link', $atts );

}

add_action( 'after_setup_theme', 'power_register_nav_menus' );
/**
 * Register the custom menu locations, if theme has support for them.
 *
 * Does the `power_register_nav_menus` action.
 *
 * @since 1.8.0
 *
 * @return void Return early if `power-menus` are not supported.
 */
function power_register_nav_menus() {

	if ( ! current_theme_supports( 'power-menus' ) ) {
		return;
	}

	$menus = get_theme_support( 'power-menus' );

	register_nav_menus( (array) $menus[0] );

	/**
	 * Fires after registering custom Power navigation menus.
	 *
	 * @since 1.8.0
	 */
	do_action( 'power_register_nav_menus' );

}

add_action( 'power_after_header', 'power_do_nav' );
/**
 * Echo the "Primary Navigation" menu.
 *
 * Applies the `power_do_nav` filter.
 *
 * @since 1.0.0
 */
function power_do_nav() {

	// Do nothing if menu not supported.
	if ( ! power_nav_menu_supported( 'primary' ) || ! has_nav_menu( 'primary' ) ) {
		return;
	}

	$class = 'menu power-nav-menu menu-primary';
	if ( power_superfish_enabled() ) {
		$class .= ' js-superfish';
	}

	power_nav_menu(
		[
			'theme_location' => 'primary',
			'menu_class'     => $class,
		]
	);

}

add_action( 'power_after_header', 'power_do_subnav' );
/**
 * Echo the "Secondary Navigation" menu.
 *
 * Applies the `power_do_subnav` filter.
 *
 * @since 1.0.0
 */
function power_do_subnav() {

	// Do nothing if menu not supported.
	if ( ! power_nav_menu_supported( 'secondary' ) ) {
		return;
	}

	$class = 'menu power-nav-menu menu-secondary';
	if ( power_superfish_enabled() ) {
		$class .= ' js-superfish';
	}

	power_nav_menu(
		[
			'theme_location' => 'secondary',
			'menu_class'     => $class,
		]
	);

}
