<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Sidebars
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    daniellane.eu
 */

add_action( 'power_sidebar', 'power_do_sidebar' );
/**
 * Echo primary sidebar default content.
 *
 * Only shows if sidebar is empty, and current user has the ability to edit theme options (manage widgets).
 *
 * @since 1.2.0
 */
function power_do_sidebar() {

	if ( ! dynamic_sidebar( 'sidebar' ) && current_user_can( 'edit_theme_options' ) ) {
		power_default_widget_area_content( __( 'Primary Sidebar Widget Area', 'power' ) );
	}

}

add_action( 'power_sidebar_alt', 'power_do_sidebar_alt' );
/**
 * Echo alternate sidebar default content.
 *
 * Only shows if sidebar is empty, and current user has the ability to edit theme options (manage widgets).
 *
 * @since 1.2.0
 */
function power_do_sidebar_alt() {

	if ( ! dynamic_sidebar( 'sidebar-alt' ) && current_user_can( 'edit_theme_options' ) ) {
		power_default_widget_area_content( __( 'Secondary Sidebar Widget Area', 'power' ) );
	}

}

/**
 * Template for default widget area content.
 *
 * @since 2.0.0
 *
 * @param string $name Name of the widget area e.g. `__( 'Secondary Sidebar Widget Area', 'yourtextdomain' )`.
 */
function power_default_widget_area_content( $name ) {

	power_markup(
		[
			'open'    => '<section class="widget widget_text">',
			'context' => 'default-widget-content-wrap',
		]
	);

	echo '<div class="widget-wrap">';

		$power_heading = ( power_a11y( 'headings' ) ? 'h3' : 'h4' );

		echo sprintf( '<%1$s class="widgettitle">%2$s</%1$s>', esc_attr( $power_heading ), esc_html( $name ) );
		echo '<div class="textwidget"><p>';
			printf(
				/* translators: 1: Widget name, 2: URL to widgets admin page. */
				esc_html__( 'This is the %1$s. You can add content to this area by visiting your %2$s and adding new widgets to this area.', 'power' ),
				esc_html( $name ),
				sprintf(
					'<a href="%1$s">%2$s</a>',
					esc_url( admin_url( 'widgets.php' ) ),
					esc_html__( 'Widgets Panel', 'power' )
				)
			);

		echo '</p></div>';

	echo '</div>';

	power_markup(
		[
			'close'   => '</section>',
			'context' => 'default-widget-content-wrap',
		]
	);

}
