<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    Core Engine
 */

?>
<h3><?php esc_html_e( 'Layout Settings', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'This lets you select the layout for the archive page. On most of the child themes you\'ll see these options:', 'power' ); ?>
</p>
<ul>
	<li><?php esc_html_e( 'Content Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Content Sidebar Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Sidebar Content', 'power' ); ?></li>
	<li><?php esc_html_e( 'Full Width Content', 'power' ); ?></li>
</ul>
<p>
	<?php esc_html_e( 'These options can be extended or limited by the child theme.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type\'s archive page.', 'power' ); ?>
</p>
