<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Archive Settings', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'The Archive Headline sets the title seen on the archive page.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'The Archive Intro Text sets the text before the archive entries to introduce the content to the viewer.', 'power' ); ?>
</p>
