<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Export', 'power' ); ?></h3>
<p>
	<?php
	/* translators: %s: Abbreviation element for "JSON". */
	printf( esc_html__( 'You can export your Power-related settings to back them up, or copy them to another site. Child themes and plugins may add their own checkboxes to the list. The settings are exported in %s format.', 'power' ), '<abbr title="' . esc_html__( 'JavaScript Object Notation', 'power' ) . '">' . esc_html__( 'JSON', 'power' ) . '</abbr>' );
	?>
</p>
