<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Import/Export', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'This allows you to import or export Power Settings.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'This is specific to Power settings and does not includes posts, pages, or images, which is what the built-in WordPress import/export menu does.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'It also does not include other settings for plugins, widgets, or post/page/term/user specific settings.', 'power' ); ?>
</p>
