<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Blog Page', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'This works with the Blog Template, which is a page template that shows your latest posts. It\'s what people see when they land on your homepage.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'In the General Settings you can select a specific category to display from the drop down menu, and exclude categories by ID, or even select how many posts you\'d like to display on this page.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'There are some special features of the Blog Template that allow you to specify which category to show on each page using the template, which is helpful if you have a "News" category (or something else) that you want to display separately.', 'power' ); ?>
</p>
<p>
	<?php
	/* translators: 1: Open anchor tag, 2: Close anchor tag. */
	printf( esc_html__( 'You can find more on this feature in the %1$sHow to Add a Post Category Page tutorial.%2$s', 'power' ), '<a href="https://www.www.daniellane.eu" target="_blank" rel="noopener noreferrer">', '</a>' );
	?>
</p>
