<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Navigation', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'The Primary Navigation Extras typically display on the right side of your Primary Navigation menu.', 'power' ); ?>
</p>
<ul>
	<li><?php esc_html_e( 'Today\'s date displays the current date', 'power' ); ?></li>
	<li><?php esc_html_e( 'RSS feed link displays a link to the RSS feed for your site that a reader can use to subscribe to your site using the feedreader of their choice.', 'power' ); ?></li>
	<li><?php esc_html_e( 'Search form displays a small search form utilizing the WordPress search functionality.', 'power' ); ?></li>
	<li><?php esc_html_e( 'Twitter link displays a link to your Twitter profile, as indicated in Twitter ID setting. Enter only your user name in this setting.', 'power' ); ?></li>
</ul>
<p>
	<?php esc_html_e( 'These options can be extended or limited by the child theme.', 'power' ); ?>
</p>
