<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<p>
	<strong><?php esc_html_e( 'Document Title', 'power' ); ?></strong>
	<?php esc_html_e( ' &mdash; Output in the document <title> Tag.', 'power' ); ?>
</p>
<p>
	<strong><?php esc_html_e( 'Meta Description', 'power' ); ?></strong>
	<?php esc_html_e( ' &mdash; Output in the document <meta name="description" /> Tag.', 'power' ); ?>
</p>
<p>
	<strong><?php esc_html_e( 'Meta Keywords', 'power' ); ?></strong>
	<?php esc_html_e( ' &mdash; Output in the document <meta name="keywords" /> Tag.', 'power' ); ?>
</p>
<p>
	<strong><?php esc_html_e( 'Canonical URL', 'power' ); ?></strong>
	<?php
	/* translators: %s: Reference link. */
	printf( esc_html__( ' &mdash; Output in the document <link rel="canonical" />. %s', 'power' ), '<a href="http://www.mattcutts.com/blog/canonical-link-tag/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Read more about Custom Canonical URL', 'power' ) . '</a>' );
	?>
</p>
<p>
	<strong><?php esc_html_e( 'Custom Redirect URL', 'power' ); ?></strong>
	<?php
	/* translators: %s: Reference link. */
	printf( esc_html__( ' &mdash; Redirect this post/page to this URL. %s.', 'power' ), '<a href="http://www.google.com/support/webmasters/bin/answer.py?hl=en&amp;answer=93633" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Read more about 301 Redirects', 'power' ) . '</a>' );
	?>
</p>
<p>
	<strong><?php esc_html_e( 'Apply noindex to this post/page', 'power' ); ?></strong>
	<?php
	/* translators: %s: Reference link. */
	printf( esc_html__( ' &mdash; Output in the document <meta name="robots" />. %s', 'power' ), '<a href="http://yoast.com/articles/robots-meta-tags/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Read more about noindex', 'power' ) . '</a>' );
	?>
</p>
<p>
	<strong><?php esc_html_e( 'Apply nofollow to this post/page', 'power' ); ?></strong>
	<?php
	/* translators: %s: Reference link. */
	printf( esc_html__( ' &mdash; Output in the document <meta name="robots" />. %s', 'power' ), '<a href="http://yoast.com/articles/robots-meta-tags/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Read more about nofollow', 'power' ) . '</a>' );
	?>
</p>
<p>
	<strong><?php esc_html_e( 'Apply noarchive to this post/page', 'power' ); ?></strong>
	<?php
	/* translators: %s: Reference link. */
	printf( esc_html__( ' &mdash; Output in the document <meta name="robots" />. %s.', 'power' ), '<a href="http://yoast.com/articles/robots-meta-tags/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Read more about noarchive', 'power' ) . '</a>' );
	?>
</p>
