<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Information', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'The information box allows you to see the current Power theme information and display if desired.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'Normally, this should be unchecked. You can also set to enable automatic updates.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'This does not mean the updates happen automatically without your permission; it will just notify you that an update is available. You must select it to perform the update.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'If you provide an email address, your site will email you when the update can be performed.', 'power' ); ?>
</p>
