<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Default Layout', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'This lets you select the default layout for your entire site. On most of the child themes you\'ll see these options:', 'power' ); ?>
</p>
<ul>
	<li><?php esc_html_e( 'Content Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Content Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Content Sidebar Sidebar', 'power' ); ?></li>
	<li><?php esc_html_e( 'Sidebar Sidebar Content', 'power' ); ?></li>
	<li><?php esc_html_e( 'Full Width Content', 'power' ); ?></li>
</ul>
<p>
	<?php esc_html_e( 'These options can be extended or limited by the child theme. Additionally, many of the child themes do not allow different layouts on the home page as they have been designed for a specific home page layout.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'This layout can also be overridden in the post/page/term layout options on each post/page/term.', 'power' ); ?>
</p>
