<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'SEO Settings', 'power' ); ?></h3>
<p>
	<?php esc_html_e( 'Power SEO (search engine optimization) is polite, and will disable itself when most popular SEO plugins (e.g., All-in-One SEO, WordPress SEO, etc.) are active.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'If you don’t see an SEO Settings sub menu, then you probably have another SEO plugin active.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'If you see the menu, then opening that menu item will let you set the General SEO settings for your site.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'Each page, post, and term will have its own SEO settings as well. The default settings are recommended for most users. If you wish to adjust your SEO settings, the boxes include internal descriptions.', 'power' ); ?>
</p>
<p>
	<?php esc_html_e( 'Below you\'ll find a few succinct notes on the options for each box:', 'power' ); ?>
</p>
