<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<h3><?php esc_html_e( 'Doctitle Settings', 'power' ); ?></h3>
<p>
	<?php
	/* translators: 1: Open strong tag, 2: Close strong tag. */
	printf( esc_html__( '%1$sAppend Site Description%2$s will insert the site description from your General Settings after the title on your home page.', 'power' ), '<strong>', '</strong>' );
	?>
</p>
<p>
	<?php
	/* translators: 1: Open strong tag, 2: Close strong tag. */
	printf( esc_html__( '%1$sAppend Site Name%2$s will put the site name from the General Settings after the title on inner page.', 'power' ), '<strong>', '</strong>' );
	?>
</p>
<p>
	<?php
	/* translators: 1: Open strong tag, 2: Close strong tag. */
	printf( esc_html__( '%1$sDoctitle Append Location%2$s determines which side of the title to add the previously mentioned items.', 'power' ), '<strong>', '</strong>' );
	?>
</p>
<p>
	<?php
	/* translators: 1: Open strong tag, 2: Close strong tag. */
	printf( esc_html__( 'The %1$sDoctitle Separator%2$s is the character that will go between the title and appended text.', 'power' ), '<strong>', '</strong>' );
	?>
</p>
