<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Handle for Power_Admin_Meta_Boxes class.
 *
 * @since 2.5.0
 *
 * @return Power_Admin_Meta_Boxes Instance of class for registering meta boxes added to WordPress admin screens.
 */
function power_meta_boxes() {

	static $meta_boxes = null;

	if ( null === $meta_boxes ) {
		$meta_boxes = new Power_Admin_Meta_Boxes();
	}

	return $meta_boxes;

}
