<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_action( 'customize_register', 'power_customize_register' );
/**
 * Include, instantiate, and initialize the Power Customizer object.
 *
 * @since 2.6.0
 *
 * @param WP_Customize_Manager $wp_customize WP Customizer Manager object.
 */
function power_customize_register( WP_Customize_Manager $wp_customize ) {

	$power_customizer = new Power_Customizer( $wp_customize );
	$power_customizer->init();

}

add_action( 'power_customizer', 'power_customizer_theme_settings' );
/**
 * Build the Theme Settings Customizer panels, sections, and controls.
 *
 * @since 2.6.0
 *
 * @param Power_Customizer $power_customizer Power Customizer object.
 */
function power_customizer_theme_settings( Power_Customizer $power_customizer ) {

	$config = power_get_config( 'customizer-theme-settings' );

	/**
	 * Filter the `$config` array, built from /config/customizer-theme-settings.php.
	 *
	 * @since 2.6.0
	 *
	 * @param array $config The config array for theme settings in the Customizer.
	 */
	$config = apply_filters( 'power_customizer_theme_settings_config', $config );

	$power_customizer->register( $config );

}

add_action( 'power_customizer', 'power_customizer_seo_settings' );
/**
 * Build the SEO Settings Customizer panels, sections, and controls.
 *
 * @since 2.6.0
 *
 * @param Power_Customizer $power_customizer Power Customizer object.
 */
function power_customizer_seo_settings( Power_Customizer $power_customizer ) {

	$config = power_get_config( 'customizer-seo-settings' );

	/**
	 * Filter the `$config` array, built from /config/customizer-seo-settings.php.
	 *
	 * @since 2.6.0
	 *
	 * @param array $config The config array for seo settings in the Customizer.
	 */
	$config = apply_filters( 'power_customizer_seo_settings_config', $config );

	$power_customizer->register( $config );

}

/**
 * Return array of color scheme choices for the Customizer.
 *
 * @since 2.6.0
 *
 * @return array Choices of color schemes.
 */
function power_get_color_schemes_for_customizer() {
	if ( ! power_has_color_schemes() ) {
		return [];
	}

	$color_schemes = get_theme_support( 'power-style-selector' );

	return array_merge(
		[ '' => __( 'Default', 'power' ) ],
		array_shift( $color_schemes )
	);
}

/**
 * Return true if color schemes are registered.
 *
 * @since 2.6.0
 *
 * @return bool True if color schemes are registered, false otherwise.
 */
function power_has_color_schemes() {
	if ( ! current_theme_supports( 'power-style-selector' ) ) {
		return false;
	}

	$schemes = get_theme_support( 'power-style-selector' );

	return is_array( $schemes ) && count( $schemes[0] ) >= 1;
}

/**
 * Return true if Header section in Customizer -> Theme Settings should be shown.
 *
 * @since 2.6.0
 *
 * @return bool True if Header section should be shown, false otherwise.
 */
function power_show_header_customizer_callback() {
	return ! current_theme_supports( 'power-custom-header' ) && ! current_theme_supports( 'custom-header' ) && ! current_theme_supports( 'power-custom-logo' );
}

/**
 * Return true if user has chosen to show posts on the front page.
 *
 * @since 2.6.0
 *
 * @return bool True if posts is selected, false otherwise.
 */
function power_posts_show_on_front() {
	return 'posts' === get_option( 'show_on_front' );
}

/**
 * Return true if user has chosen to show a static page on the front page.
 *
 * @since 2.6.0
 *
 * @return bool True if static page is selected, false otherwise.
 */
function power_page_show_on_front() {
	return 'page' === get_option( 'show_on_front' );
}

add_filter( 'power_customizer_theme_settings_config', 'power_add_singular_image_output_customizer_checkboxes' );
/**
 * Return the config that includes the power_single controls.
 *
 * @since 3.1.0
 *
 * @param array $config Config array.
 *
 * @return array New config including the power_single controls.
 */
function power_add_singular_image_output_customizer_checkboxes( $config ) {

	if ( ! isset( $config['power']['sections']['power_single'] ) ) {
		return;
	}

	$types_with_singular_images_support = get_post_types_by_support( 'power-singular-images' );

	$controls = [];

	if ( isset( $config['power']['sections']['power_single']['controls'] ) ) {
		$controls = $config['power']['sections']['power_single']['controls'];
	}

	foreach ( $types_with_singular_images_support as $type ) {
		if ( ! post_type_exists( $type ) ) {
			continue;
		}
		$post_type = get_post_type_object( $type );

		$controls[ "show_featured_image_${type}" ] = [
			// translators: the post type label.
			'label'    => sprintf( __( 'Show Featured Images on %s', 'power' ), $post_type->label ),
			'section'  => 'power_single',
			'type'     => 'checkbox',
			'settings' => [
				'default' => 0,
			],
		];
	}

	$config['power']['sections']['power_single']['controls'] = $controls;

	return $config;
}
