<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package CoreEngine\Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_filter( 'update_right_now_text', 'power_update_right_now_text' );
/**
 * Callback to amend the Right Now text, found in the At A Glance dashboard widget.
 *
 * @since 2.7.0
 *
 * @param string $content Existing Right Now text.
 * @return string Amended Right Now text.
 */
function power_update_right_now_text( $content ) {
	$string = sprintf(
		/* translators: %s: Power theme version */
		esc_html__( ' Using Power %s.', 'power' ),
		PARENT_THEME_VERSION
	);

	return $content . $string;
}
