<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_filter( 'debug_information', 'power_site_health_info' );
/**
 * Adds Power info to the Tools -> Site Health -> Info tab.
 *
 * @since 3.0.0
 *
 * @param array $info The original debug information.
 * @return array Debug information modified with Power information.
 */
function power_site_health_info( $info ) {
	$options = get_option( POWER_SETTINGS_FIELD );

	if ( ! is_array( $options ) ) {
		return $info;
	}

	$info['power'] = [
		'label' => __( 'Power', 'power' ),
	];

	foreach ( $options as $name => $value ) {
		if ( $value ) {
			$info['power']['fields'][ $name ] = [
				'label'   => $name,
				'value'   => $value,
				'private' => 'update_email_address' === $name,
			];
		}
	}

	return $info;
}

add_filter( 'debug_information', 'power_child_theme_recommendations' );
/**
 * Adds child theme recommendations to the Tools -> Site Health -> Info tab
 * under the “Active Theme” panel.
 *
 * @since 3.0.0
 *
 * @param array $info The original debug information.
 * @return array Debug information modified with Power recommendations.
 */
function power_child_theme_recommendations( $info ) {
	$deprecated_theme_supports = power_get_child_theme_recommendations();

	if ( $deprecated_theme_supports ) {
		$info['wp-active-theme']['fields']['power_recommendations'] = [
			'label'   => __( 'Power recommendations', 'power' ),
			'value'   => $deprecated_theme_supports,
			'private' => false,
		];
	}

	return $info;
}

/**
 * Gets recommendations for the active child theme.
 *
 * Helps surface deprecated Power features still being used in themes.
 *
 * @since 3.0.0
 *
 * @return string|void Suggestions for improvement, or void if no suggestions.
 */
function power_get_child_theme_recommendations() {
	if ( ! is_child_theme() ) {
		return;
	}

	$recommendations = [];

	if ( get_theme_support( 'power-responsive-viewport' ) ) {
		$recommendations[] = '"power-responsive-viewport" theme support can be removed';
	}

	$accessibility_support = get_theme_support( 'power-accessibility' );

	if ( $accessibility_support && in_array( '404-page', $accessibility_support[0], true ) ) {
		$recommendations[] = __( '"404-page" no longer required in "power-accessibility" theme support array', 'power' );
	}

	if ( $recommendations ) {
		$message = __( 'This theme uses theme supports that are no longer required in Power 3.0+: ', 'power' );
		return $message . implode( ', ', $recommendations );
	}
}
