<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Admin
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_action( 'admin_notices', 'power_use_child_theme_notice' );

/**
 * Display Warning that Power should always be used with a child theme.
 *
 * @since 2.3.0
 */
function power_use_child_theme_notice() {

	if ( is_child_theme() ) {
		return;
	}

	$allowed_html = [
		'a' => [
			'href' => [],
		],
	];

	include POWER_VIEWS_DIR . '/misc/use-child-theme-notice.php';

}
