<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Options
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

add_action( 'power_meta', 'power_load_stylesheet' );
/**
 * Echo reference to the style sheet.
 *
 * If a child theme is active, it loads the child theme's stylesheet, otherwise, it loads the Power style sheet.
 *
 * @since 1.0.0
 *
 * @see power_enqueue_main_stylesheet() Enqueue main style sheet.
 */
function power_load_stylesheet() {

	add_action( 'wp_enqueue_scripts', 'power_enqueue_main_stylesheet', 5 );

}

/**
 * Enqueue main style sheet.
 *
 * Properly enqueue the main style sheet.
 *
 * @since 1.9.0
 */
function power_enqueue_main_stylesheet() {

	wp_enqueue_style(
		power_get_theme_handle(),
		get_stylesheet_uri(),
		false,
		power_get_theme_version()
	);

}

add_action( 'admin_print_styles', 'power_load_admin_styles' );
/**
 * Enqueue Power admin styles.
 *
 * @since 1.0.0
 */
function power_load_admin_styles() {

	$suffix = power_is_in_dev_mode() ? '' : '.min';

	wp_enqueue_style( 'power_admin_css', POWER_CSS_URL . "/admin{$suffix}.css", [], PARENT_THEME_VERSION );

	if ( is_rtl() ) {
		wp_enqueue_style( 'power_admin_rtl_css', POWER_CSS_URL . "/admin-rtl{$suffix}.css", [], PARENT_THEME_VERSION );
	}

}
