<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\Power
 * @author  Core Engine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

?>
<div class="error"><p>
	<strong><?php esc_html_e( 'Please Activate a Power Child Theme:', 'power' ); ?></strong>
	<?php
	esc_html_e( 'We\'ve noticed you are using the Power Framework parent theme alone. We strongly recommend you run a Power child theme with it (we even have a free theme you can use). ', 'power' );
	printf(
		/* translators: %s: URL to coreengine.com. */
		esc_html__( 'For more information, see our article at %s', 'power' ),
		sprintf(
			'<a href="%1$s">%2$s</a>',
			esc_url( 'https://www.coreengine.com/power-always-use-child-theme/' ),
			esc_html( 'https://www.coreengine.com/power-always-use-child-theme/' )
		)
	);
	?>
</p></div>
