<?php
/**
 * Power Framework.
 *
 * WARNING: This file is part of the core Power Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Power\SEO
 * @author  CoreEngine
 * @license GPL-2.0-or-later
 * @link    www.daniellane.eu
 */

/**
 * Disable the Power SEO features.
 *
 * @since 1.6.0
 *
 * @see power_default_title()
 * @see power_doc_head_control()
 * @see power_seo_meta_description()
 * @see power_seo_meta_keywords()
 * @see power_robots_meta()
 * @see power_canonical()
 * @see power_add_inpost_seo_box()
 * @see power_add_inpost_seo_save()
 * @see power_add_taxonomy_seo_options()
 * @see power_user_seo_fields()
 */
function power_disable_seo() {

	remove_filter( 'wp_title', 'power_default_title', 10 );
	remove_action( 'get_header', 'power_doc_head_control' );
	remove_action( 'power_meta', 'power_seo_meta_description' );
	remove_action( 'power_meta', 'power_seo_meta_keywords' );
	remove_action( 'power_meta', 'power_robots_meta' );
	remove_action( 'wp_head', 'power_canonical', 5 );
	remove_action( 'wp_head', 'power_meta_name' );
	remove_action( 'wp_head', 'power_meta_url' );
	remove_action( 'wp_head', 'power_paged_rel' );
	remove_filter( 'power_attr_head', 'power_attributes_head' );
	add_filter( 'power_attr_head', 'power_attributes_empty_class' );

	remove_action( 'admin_menu', 'power_add_inpost_seo_box' );
	remove_action( 'save_post', 'power_inpost_seo_save', 1 );

	remove_action( 'admin_init', 'power_add_taxonomy_seo_options' );

	remove_action( 'show_user_profile', 'power_user_seo_fields' );
	remove_action( 'edit_user_profile', 'power_user_seo_fields' );

	remove_theme_support( 'power-seo-settings-menu' );
	add_filter( 'pre_option_' . POWER_SEO_SETTINGS_FIELD, '__return_empty_array' );

	define( 'POWER_SEO_DISABLED', true );

}

/**
 * Detect whether or not Power SEO has been disabled.
 *
 * @since 1.8.0
 *
 * @return bool `true` if Power SEO is disabled, `false` otherwise.
 */
function power_seo_disabled() {

	return defined( 'POWER_SEO_DISABLED' ) && POWER_SEO_DISABLED;

}

/**
 * Detect whether Power SEO is active.
 *
 * @since 2.6.0
 *
 * @return bool `true` if Power SEO is active, `false` otherwise.
 */
function power_seo_active() {
	return ! power_seo_disabled();
}

add_action( 'after_setup_theme', 'power_seo_compatibility_check' );
/**
 * Check for the existence of popular SEO plugins and disable the Power SEO features if one or more of the plugins
 * is active.
 *
 * Runs before the menu is built, so we can disable SEO Settings menu, if necessary.
 *
 * @since 1.2.0
 *
 * @see power_default_title()
 */
function power_seo_compatibility_check() {

	if ( power_detect_seo_plugins() ) {
		power_disable_seo();
	}

	if ( ! power_is_wpseo_outputting_jsonld() && ! apply_filters( 'power_disable_microdata', false ) ) {
		include_once dirname( __FILE__ ) . '/schema.php';
	}

	// Disable Power <title> generation if SEO Title Tag is active.
	if ( function_exists( 'seo_title_tag' ) ) {
		remove_filter( 'wp_title', 'power_default_title', 10 );
		remove_action( 'power_title', 'wp_title' );
		add_action( 'power_title', 'seo_title_tag' );
	}

}

/**
 * Detect some SEO Plugin that add constants, classes or functions.
 *
 * Applies `power_detect_seo_plugins` filter to allow third party manipulation of SEO plugin list.
 *
 * @since 1.6.0
 *
 * @return bool `true` if plugin exists, or `false` if plugin constant, class or function not detected.
 */
function power_detect_seo_plugins() {

	return power_detect_plugin(
		// Use this filter to adjust plugin tests.
		apply_filters(
			'power_detect_seo_plugins',
			// Add to this array to add new plugin checks.
			[

				// Classes to detect.
				'classes'   => [
					'All_in_One_SEO_Pack',
					'All_in_One_SEO_Pack_p',
					'HeadSpace_Plugin',
					'Platinum_SEO_Pack',
					'wpSEO',
					'SEO_Ultimate',
				],

				// Functions to detect.
				'functions' => [],

				// Constants to detect.
				'constants' => [ 'WPSEO_VERSION', 'SEOPRESS_VERSION' ],
			]
		)
	);

}

add_action( 'save_post', 'power_maybe_clear_primary_title_h1' );
/**
 * Sets the Primary Title H1 Power SEO setting to None if a heading level one
 * is found on a static homepage.
 *
 * @since 3.1.0
 *
 * @param int $post_id The page to check for an h1.
 */
function power_maybe_clear_primary_title_h1( $post_id ) {

	if (
		! $post_id
		|| power_seo_disabled()
		|| wp_is_post_revision( $post_id )
		|| ! has_blocks( $post_id )
	) {
		return;
	}

	if ( 'page' !== get_option( 'show_on_front' ) ) {
		return;
	}

	if ( (int) get_option( 'page_on_front' ) !== $post_id ) {
		return;
	}

	$seo_options = get_option( POWER_SEO_SETTINGS_FIELD );

	if ( 'neither' === $seo_options['home_h1_on'] ) {
		return;
	}

	$post = get_post( $post_id );

	if ( ! $post instanceof WP_Post ) {
		return;
	}

	$post_has_h1_block = preg_match( '/wp:heading {.+1.*}/', $post->post_content );

	if ( $post_has_h1_block ) {
		$seo_options['home_h1_on'] = 'neither';
		update_option( POWER_SEO_SETTINGS_FIELD, $seo_options );
	}

}

/**
 * Determines if JSON-LD is enabled from 3rd party plugins.
 *
 * @since 3.1.0
 *
 * @return bool True if enabled, false if else.
 */
function power_is_wpseo_outputting_jsonld() {
	$wpseo_ld_enabled = (
		defined( 'WPSEO_VERSION' )
		&& version_compare( WPSEO_VERSION, '11.0-RC0', '>=' )
		// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
		&& apply_filters( 'wpseo_json_ld_output', true )
	);

	return apply_filters( 'power_is_wpseo_outputting_jsonld', $wpseo_ld_enabled );
}
